import { Router } from 'express';
import perfilRoutes from './perfil';
import agendamientoRoutes from './agendamiento';
import historiaClinicaRoutes from './historiaClinica';
import historiaClinicaHeridasRoutes from './historia-clinica-heridas';
import heridasIaRoutes from './heridas-ia';
import formulaMedicaRoutes from './formulaMedica';
import incapacidadRoutes from './incapacidad';
import interconsultaRoutes from './interconsulta';
import examenMedicoRoutes from './examenMedico';
import apoyoTerapeuticoRoutes from './apoyoTerapeutico';
import ayudaDiagnosticaRoutes from './ayudaDiagnostica';
import videocallRoutes from './videocall';
import transcriptionRoutes from './transcription';
import materialesRoutes from './materiales';
import asesoriasRoutes from './asesorias';
import iaSimuladaRoutes from './ia-simulada';
import copilotoVozRoutes from './copiloto-voz';
import paraclinicosRoutes from './paraclinicos';
import referidosRoutes from './referidos';
import anamnesisRoutes from './anamnesis';
import seguimientoRoutes from './seguimiento';
import googleCalendarRoutes from './googleCalendar';
import metricasRoutes from './metricas';
import pagoRoutes from './pago';
import consultaRoutes from './consulta';
import iaEntrenadaRoutes from './ia-entrenada';
import chatRoutes from './chat';
import cie10Routes from './cie10';

const router = Router();

// Montar todas las rutas del módulo médico
router.use('/perfil', perfilRoutes);
router.use('/agendamiento', agendamientoRoutes);
router.use('/historia-clinica', historiaClinicaRoutes);
router.use('/historia-clinica-heridas', historiaClinicaHeridasRoutes);
router.use('/heridas-ia', heridasIaRoutes);
router.use('/formula-medica', formulaMedicaRoutes);
router.use('/incapacidad', incapacidadRoutes);
router.use('/interconsulta', interconsultaRoutes);
router.use('/examen-medico', examenMedicoRoutes);
router.use('/apoyo-terapeutico', apoyoTerapeuticoRoutes);
router.use('/ayuda-diagnostica', ayudaDiagnosticaRoutes);
router.use('/videocall', videocallRoutes);
router.use('/transcription', transcriptionRoutes);
router.use('/materiales', materialesRoutes);
router.use('/asesorias', asesoriasRoutes);
router.use('/ia-simulada', iaSimuladaRoutes);
router.use('/copiloto-voz', copilotoVozRoutes);
router.use('/paraclinicos', paraclinicosRoutes);
router.use('/mis-referidos', referidosRoutes);
router.use('/anamnesis', anamnesisRoutes);
router.use('/seguimiento', seguimientoRoutes);
router.use('/google-calendar', googleCalendarRoutes);
router.use('/metricas', metricasRoutes);
router.use('/pago', pagoRoutes);
router.use('/consulta', consultaRoutes);
router.use('/ia-entrenada', iaEntrenadaRoutes);
router.use('/chat', chatRoutes);
router.use('/cie10', cie10Routes);

export default router;

