import { Router } from 'express';
import { authenticate, authorize } from '../../middleware/auth';
import { UserRole } from '../../types';
import { infoCitaHeridas, getMeetingHeridas } from '../../controllers/paciente/heridasPacienteController';
import { responder as responderCuerpoChat, precargar as precargarCuerpoChat } from '../../controllers/paciente/cuerpoConChatController';
import perfilRoutes from './perfil';
import agendamientoRoutes from './agendamiento';
import interrogatorioRoutes from './interrogatorio';
import documentosRoutes from './documentos';
import asesoriasRoutes from './asesorias';
import paraclinicosRoutes from './paraclinicos';
import formulaMedicaRoutes from './formula-medica';
import pagoRoutes from './pago';
import ordenExamenesRoutes from './orden-examenes';
import alimentosRoutes from './alimentos';
import recomendacionRoutes from './recomendacion';
import codigoDescuentoRoutes from './codigo-descuento';
import cuidadorIARoutes from './cuidador-ia';
import invitarMedicoRoutes from './invitar-medico';
import historiaClinicaRoutes from './historia-clinica';
import tratamientoRoutes from './tratamiento';
import transcriptionRoutes from './transcription';
import chatRoutes from './chat';
import wearablesRoutes from './wearables';
// import consultaRapidaRoutes from './consulta-rapida';

const router = Router();

router.use('/perfil', perfilRoutes);
router.use('/agendamiento', agendamientoRoutes);
router.use('/interrogatorio', interrogatorioRoutes);
router.use('/documentos', documentosRoutes);
router.use('/asesorias', asesoriasRoutes);
router.use('/paraclinicos', paraclinicosRoutes);
router.use('/formula-medica', formulaMedicaRoutes);
router.use('/pago', pagoRoutes);
router.use('/orden-examenes', ordenExamenesRoutes);
router.use('/alimentos', alimentosRoutes);
router.use('/recomendacion', recomendacionRoutes);
router.use('/codigo-descuento', codigoDescuentoRoutes);
router.use('/cuidador-ia', cuidadorIARoutes);
router.use('/invitar-medico', invitarMedicoRoutes);
router.use('/historia-clinica', historiaClinicaRoutes);
router.use('/tratamiento', tratamientoRoutes);
router.use('/transcription', transcriptionRoutes);
router.use('/chat', chatRoutes);
router.use('/wearables', wearablesRoutes);
// router.use('/consulta-rapida', consultaRapidaRoutes);

router.get('/heridas-cita/:citaId/info', authenticate, authorize(UserRole.PACIENTE), infoCitaHeridas);
router.get('/heridas-cita/:citaId/meeting', authenticate, authorize(UserRole.PACIENTE), getMeetingHeridas);
router.post('/cuerpo-chat', authenticate, authorize(UserRole.PACIENTE), responderCuerpoChat);
router.post('/cuerpo-chat/precargar', authenticate, authorize(UserRole.PACIENTE), precargarCuerpoChat);

export default router;
