name: Backend - Backend Nutrabiotics 

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/CrisaliaBack"

      - name: Ejecutar comandos en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/CrisaliaBack

            echo "Instalando dependencias..."
            npm install

            echo "Reiniciando backend..."

            pm2 delete backend-nutrabiotics || true

            pm2 start src/server.ts \
              --name backend-nutrabiotics \
              --interpreter npx \
              --interpreter-args ts-node

            pm2 save

            echo "Deploy finalizado correctamente"
